export const tldrawShape = {
  x: 311,
  y: 130,
  rotation: 0,
  isLocked: false,
  opacity: 1,
  meta: {},
  id: 'shape:id',
  type: 'geo',
  props: {
    w: 486,
    h: 302.99999999999994,
    geo: 'rectangle',
    color: 'black',
    labelColor: 'black',
    fill: 'none',
    dash: 'draw',
    size: 'm',
    font: 'draw',
    align: 'middle',
    verticalAlign: 'middle',
    growY: 0,
    url: '',
    scale: 1,
    richText: {
      type: 'doc',
      content: [
        {
          type: 'paragraph',
          attrs: { dir: 'auto' },
          content: [{ type: 'text', text: 'test abc' }],
        },
      ],
    },
  },
  parentId: 'page:page',
  index: 'a1',
  typeName: 'shape',
};
